# Generated by Django 4.0.1 on 2022-02-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('total_target', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('general_rate', models.IntegerField()),
                ('is_deleted', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
                ('tag_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tags')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
    ]
