# Generated by Django 4.0.1 on 2022-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='total_target',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
