# Generated by Django 4.0.1 on 2022-02-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projects_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='category',
            new_name='category_id',
        ),
    ]
