# Generated by Django 4.0.1 on 2022-02-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
        ('projects', '0012_projects_tags_delete_projecttags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
    ]
