# Generated by Django 4.0.1 on 2022-02-18 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_projects_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(default=1, upload_to='project_img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.projectimages'),
            preserve_default=False,
        ),
    ]
