# Generated by Django 4.0.1 on 2022-02-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_rename_user_id_projects_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='main_photo',
            field=models.ImageField(default=1, upload_to='projects/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='projects/slider/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.images'),
        ),
    ]
