# Generated by Django 4.0.1 on 2022-02-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(to='projects.Tags'),
        ),
        migrations.DeleteModel(
            name='ProjectTags',
        ),
    ]
