# Generated by Django 4.0.1 on 2022-02-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projects_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='user_id',
        ),
    ]
