# Generated by Django 4.0.1 on 2022-02-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_projects_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='user_id',
            new_name='user',
        ),
    ]
