# Generated by Django 4.0.1 on 2022-02-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_remove_project_general_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
    ]
