# Generated by Django 4.0.1 on 2022-02-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_remove_images_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
