# Generated by Django 4.0.1 on 2022-02-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
        ('projects', '0041_remove_image_project_remove_project_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_target', models.FloatField()),
                ('total_upvotes', models.IntegerField(blank=True, default=0, null=True)),
                ('total_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('collected_donations', models.IntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('main_photo', models.ImageField(upload_to='projects/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('tags', models.ManyToManyField(to='projects.Tag')),
            ],
        ),
    ]
