# Generated by Django 4.0.1 on 2022-02-20 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
        ('projects', '0044_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('value', models.CharField(choices=[('bully', 'Bully'), ('disrespectful behavior ', 'Disrespectful Behavior'), ('fraud', 'Fraud')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('owner', 'project')},
            },
        ),
    ]
